### ISSUE TITLE
Client generates [a-d].tile.nextzen.org URIs for tiles which no longer work

### ISSUE THREAD

**Issue by azaroth42** [sfomuseum/go-placeholder-client-www#15]
And should be instead, from nextzen devs, just tile.nextzen.org.

the [a-d] requests get an SSL CYPHER error.

Thanks!

**Comment by thisisaaronland** [comment]
This should be fixed as of: https://github.com/sfomuseum/go-placeholder-client-www/releases/tag/v0.5.1
